name: subscription_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.3.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  video_player: ^2.9.2
  chewie: ^1.8.5
  url_launcher: ^6.3.0
  app_links: ^6.0.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
